name: Delete Merged Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'   # Daily at 1 AM UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure complete history

      - name: Delete merged branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.repository_default_branch }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch origin --prune

          merged=$(git branch -r --merged origin/$DEFAULT_BRANCH \
            | grep -v "origin/$DEFAULT_BRANCH" | grep -v 'HEAD' \
            | sed 's|origin/||')

          for branch in $merged; do
            if git ls-remote --exit-code --heads origin "$branch"; then
              echo "Deleting $branch"
              git push origin --delete "$branch"
            fi
          done
