name: Delete Merged Branches

on:
  workflow_dispatch:    # Allow manual trigger
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1 AM UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Delete merged branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git fetch --prune
          
          # Get merged remote branches except main and HEAD
          branches=$(git branch -r --merged origin/main | grep -v 'origin/main' | grep -v 'HEAD' | sed 's/origin\///')

          for branch in $branches; do
            echo "Deleting $branch"
            git push origin --delete "$branch"
          done
